---
abstract: 'a table widget for larger datasets'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::CheckDeps: 0.010
  Test::More: 0.98
  perl: 5.010001
configure_requires:
  ExtUtils::MakeMaker: 6.48
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-Table-Paged
requires:
  Tickit: 0.37
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tickit-Widget-Table-Paged
  homepage: http://search.cpan.org/dist/Tickit-Widget-Table-Paged/
version: 0.002
